package com.example.oefstarter.models

val allGroceries : List<String> =
    listOf("Bananas",
        "Apples",
        "Grapes",
        "Oranges",
        "Strawberries",
        "Avocados",
        "Potatoes",
        "Tomatoes",
        "Onions",
        "Carrots",
        "Lettuce",
        "Broccoli",
        "Peppers",
        "Celery",
        "Olives",
        "Soup",
        "Tuna",
        "Veggies",
        "Fish",
        "Ice Cream",
        "Pizza",
        "Potatoes",
        "Ready Meals",
        "Chicken",
        "Beef",
        "Pork",
        "Sausage",
        "Shrimp",
        "Crab",
        "Clams",
        "Tuna",
        "Salmon",
        "Tilapia",
        "Cheese",
        "Ham",
        "Turkey",
        "Salami",
        "Salt",
        "Sugar",
        "Pepper",
        "Oregano",
        "Cinnamon",
        "Ketchup",
        "Mayonnaise",
        "Olive Oil",
        "Tomato Sauce",
        "Hot Sauce ",
        "Chips ",
        "Crackers",
        "Pretzels",
        "Popcorn",
        "Peanuts",
        "Nuts",
        "Candy",
        "Whole Wheat",
        "White",
        "Italian",
        "Sandwich",
        "Cookies",
        "Water",
        "Coffee",
        "Milk",
        "Juice",
        "Soda",
        "Tea",
        "Spaghetti",
        "Macaroni",
        "Noodles",
        "Oats",
        "Rice",
        "Wheat",
        "Flour",
        "Baking Powder",
        "Butter",
        "Baby Food",
        "Diapers",
        "Wet Wipes",
        "Shampoo",
        "Soap",
        "Deodorant",
        "Toothpaste",
        "Dental Floss",
        "Shaving Cream",
        "Razor Blades",
        "Band-Aid",
        "Hydrogen Peroxide",
        "Alcohol",
        "Toilet Paper",
        "Paper Towels",
        "Tissues",
        "Aluminum Foil",
        "Detergent",
        "Softener",
        "Bleach",
        "Dish Soap",
        "Air Freshener",
        "Gloves",
        "Sponge",
        "Trash Bags",
        "Batteries")

val allShops : List<String> =
    listOf("Albert Heijn",
        "Aldi",
        "Alvo",
        "Au Bon Marché",
        "Bio-Planet",
        "Carrefour",
        "Cash & Fresh",
        "Champion",
        "Colruyt",
        "Cora",
        "Cru",
        "Delhaize",
        "Grand Bazar",
        "Intermarché",
        "Innovation",
        "Jawa",
        "Jumbo",
        "Lidl",
        "Louis Delhaize",
        "Makro",
        "Match",
        "OKay",
        "Prima",
        "Sarma",
        "Smatch",
        "Spar")